#!/usr/bin/env python3
"""
MIA Wearables — Glance state exporter.

Builds webapp/state.json for the MIA Glance web app from live sources:

  - homestead dashboard_state.json  ->  attention (unresolved alerts)
                                        next_up   (open maintenance tasks)
  - optional quests JSON file       ->  quests    (today's missions)

Every source is optional. Missing data renders as an honest empty state
in the app ("All clear."), never fabricated cards.

Usage:
    python tools/export_glance_state.py \
        --dashboard /path/to/mia-homestead/viewer/dashboard_state.json \
        --quests tools/quests.json \
        --out webapp/state.json

Run it on a schedule (or on demand) and re-host webapp/ — the glasses
app picks up the new state.json on next load.
"""

import argparse
import datetime as dt
import json
from pathlib import Path

SEV_MAP = {"critical": "critical", "warning": "warning", "info": "info"}
PRIO_MAP = {"critical": "critical", "high": "warning",
            "medium": "info", "low": "info"}


def parse_date(s):
    if not s:
        return None
    s = str(s).strip()
    for fmt in ("%Y-%m-%d", "%Y-%m-%d %H:%M:%S", "%Y-%m-%dT%H:%M:%S"):
        try:
            return dt.datetime.strptime(s[:19] if "T" in s or len(s) > 10 else s, fmt).date() \
                if fmt == "%Y-%m-%d" else dt.datetime.strptime(s[:19], fmt).date()
        except ValueError:
            continue
    try:
        return dt.date.fromisoformat(s[:10])
    except ValueError:
        return None


def due_line(due_date):
    d = parse_date(due_date)
    if not d:
        return "No due date set."
    today = dt.date.today()
    delta = (d - today).days
    if delta < 0:
        return f"Overdue {-delta} day{'s' if -delta != 1 else ''} (was due {d.isoformat()})."
    if delta == 0:
        return "Due today."
    return f"Due in {delta} day{'s' if delta != 1 else ''} ({d.isoformat()})."


def map_alert(a):
    parts = []
    if a.get("source"):
        parts.append(f"Source: {a['source']}")
    if a.get("last_seen"):
        parts.append(f"last seen {a['last_seen']}")
    if (a.get("occurrence_count") or a.get("repeat_count") or 1) > 1:
        parts.append(f"×{a.get('occurrence_count') or a.get('repeat_count')} occurrences")
    return {
        "id": f"alert-{a.get('id')}",
        "area": "Greenhouse",
        "title": a.get("message", "Unnamed alert"),
        "detail": ". ".join(parts) + "." if parts else "",
        "severity": SEV_MAP.get(str(a.get("severity", "info")).lower(), "info"),
        "action": "Open on phone",
    }


def map_maintenance(m):
    sev = PRIO_MAP.get(str(m.get("priority", "medium")).lower(), "info")
    d = parse_date(m.get("due_date"))
    overdue = d is not None and d < dt.date.today()
    if overdue and sev == "info":
        sev = "warning"
    detail_bits = []
    if m.get("description"):
        detail_bits.append(m["description"])
    detail_bits.append(due_line(m.get("due_date")))
    if m.get("task_type"):
        detail_bits.append(f"Type: {m['task_type']}")
    return {
        "id": f"maint-{m.get('id')}",
        "area": "Greenhouse",
        "title": m.get("title", "Unnamed task"),
        "detail": " ".join(detail_bits),
        "severity": sev,
        "action": "Open on phone",
    }


def load_json(path):
    p = Path(path)
    if not p.is_file():
        return None
    return json.loads(p.read_text())


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dashboard", default=None,
                    help="Path to homestead viewer/dashboard_state.json")
    ap.add_argument("--quests", default=None,
                    help="Path to a quests JSON file (list of {id,title,detail,xp,area})")
    ap.add_argument("--out", default="webapp/state.json")
    args = ap.parse_args()

    dash = load_json(args.dashboard) if args.dashboard else None

    attention, next_up = [], []
    dash_generated = None
    if dash:
        dash_generated = dash.get("generated_at")
        for a in dash.get("alerts", []) or []:
            attention.append(map_alert(a))
        for m in dash.get("maintenance", []) or []:
            next_up.append(map_maintenance(m))

    quests = []
    if args.quests:
        q = load_json(args.quests)
        if isinstance(q, list):
            quests = q
    else:
        # Preserve any quests already in the current state file so
        # re-exporting doesn't wipe the quest list.
        current = load_json(args.out)
        if current and isinstance(current.get("quests"), list):
            quests = current["quests"]

    state = {
        "meta": {
            "source": "live" if dash else "mock",
            "generated_at": dt.datetime.now().isoformat(timespec="seconds"),
            "dashboard_generated_at": dash_generated,
            "note": "Generated by tools/export_glance_state.py from homestead state.",
        },
        "attention": attention,
        "next_up": next_up,
        "quests": quests,
    }
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(state, indent=2))
    print(f"Wrote {out}: {len(attention)} attention, {len(next_up)} next-up, "
          f"{len(quests)} quests (source={state['meta']['source']}).")


if __name__ == "__main__":
    main()
